
export const appStrings = {
    en: {
        appTitle: "Track and Treat - Personalized Dietetics",
        languageLabel: "Language",
        welcomeHeader: "Welcome to Track and Treat!",
        navDashboard: "Dashboard",
        navProfile: "Profile & Goals",
        navPlan: "My Diet Plan",
        navTracking: "Tracking",
        navRecipes: "Recipes",
        navReports: "Report Analysis",
        navGuidance: "Nutrient Guidance",
        navSearch: "Health Search",
        navChat: "AI Assistant",
        navFeedback: "Feedback",
        
        // Dashboard
        dashSnapshotHeader: "Your Health Snapshot",
        dashBMI: "BMI",
        dashBMICalc: "Enter details to calculate.",
        dashTarget: "Daily Calorie Target",
        dashBaseGoal: "Based on TDEE & Goal",
        dashWater: "Water Today",
        dashWaterGoal: "Goal: 3.5 L",
        dashStreak: "Plan Streak",
        dashKeepUp: "Keep up the great work!",
        dashTipHeader: "Today's Tip from Track and Treat",
        dashTipInitial: "Please complete your profile details to unlock your first personalized tip from our specialized dietary algorithms!",
        dashProgressHeader: "Weekly Weight Loss Progress",
        
        // Profile
        profileHeader: "Your Essential Details & Goals",
        metricHeader: "Personal Metrics",
        labelName: "Name",
        labelAge: "Age (Years)",
        labelGender: "Gender",
        genderMale: "Male",
        genderFemale: "Female",
        genderOther: "Other",
        labelWeight: "Weight (kg)",
        labelHeight: "Height (cm)",
        labelActivity: "Activity Level",
        activitySedentary: "Sedentary (desk job)",
        activityLight: "Light (1-3 days/week exercise)",
        activityModerate: "Moderate (3-5 days/week exercise)",
        activityHigh: "High (6-7 days/week exercise)",
        activityExtreme: "Extreme (Athlete/heavy labor)",
        labelDiet: "Dietary Preference",
        dietVeg: "Vegetarian",
        dietNonVeg: "Non-Vegetarian",
        dietVegan: "Vegan",
        dietJain: "Jain",
        labelGoal: "Primary Goal",
        goalLoss: "Weight Loss",
        goalGain: "Weight Gain",
        goalMaintain: "Health Maintenance",
        goalMuscle: "Muscle Gain",
        medicalHeader: "Medical & Preferences (Specialized Details)",
        labelCondition: "Medical Conditions (Diabetes, PCOS, Thyroid, etc.)",
        labelAllergies: "Allergies & Intolerances",
        labelDislikes: "Food Dislikes / Likes",
        labelProfilePhoto: "Profile Photo",
        btnSaveProfile: "Save Profile & Generate Assessment",
        btnAiSummary: "✨ Get AI Health Summary",
        aiSummaryTitle: "AI Health Summary",
        macroGoalsHeader: "Macronutrient Goals (Grams)",
        labelProteinGoal: "Protein Goal (g)",
        labelCarbGoal: "Carbohydrate Goal (g)",
        labelFatGoal: "Fat Goal (g)",
        assessmentHeader: "Your Health Assessment Summary",
        calcBMI: "BMI",
        calcBMIStatus: "BMI Status",
        calcTDEE: "TDEE",
        calcReqCals: "Req. Calories",
        calcProtein: "Protein Goal",
        calcCarbs: "Carbs Goal",
        calcFat: "Fat Goal",
        macroHeader: "Estimated Macronutrient Distribution:",
        
        // Diet Plan
        planHeader: "My Diet Plan",
        btnGeneratePlan: "✨ Generate Detailed 3-Day Plan",
        planInitialPrompt: "Please save your profile details to see a static plan, or click the '✨ Generate Detailed 3-Day Plan' button to use the AI planner for a custom meal plan!",
        
        // Tracking
        trackerHeader: "Track Your Daily Intake",
        logHeader: "Meal Log",
        btnAnalyzeLog: "✨ Analyze Log",
        logAnalysisTitle: "Log Analysis:",
        logEmpty: "Your daily meal log will appear here.",
        logInputPlaceholder: "Log your meal (e.g., Lunch: 1 bowl Rajma, Rice, Salad) & quantity",
        logBtn: "Log Meal",
        waterHeader: "Water Intake",
        waterGoal: "Goal: 3.5 Litres",
        btnAddWater: "+ 250ml",
        servingsHeader: "Fruit/Veg Servings",
        btnAddServing: "+ Add Serving",
        reminderHeader: "Compliance Reminders",
        reminderText: "Set up custom meal and water reminders below for better compliance!",
        btnSetReminder: "Set Reminders",
        btnHideReminders: "Hide Reminders",
        newReminder: "New Reminder",
        reminderTime: "Time",
        reminderType: "Type",
        reminderMeal: "Meal",
        reminderWater: "Water",
        btnAddReminder: "Add Reminder",
        noRemindersSet: "No reminders set yet.",

        // Recipes
        recipesMainHeader: "Personalized Recipes & Ingredient Explorer",
        recipeDiagHeader: "Recipes for My Condition",
        recipeDiagStatus: "Click below to generate specialized recipes based on your saved medical condition",
        btnGenerateDiag: "Generate Recipes for Condition",
        recipeIngrHeader: "Innovative Ingredient Recipes",
        ingrInputPlaceholder: "Enter one main ingredient (e.g., Paneer, Bajra, Okra)",
        btnSuggestRecipes: "Suggest 3 Innovative Recipes",
        
        // Reports
        reportsMainHeader: "Medical Report Interpretation",
        reportsAnalyzeHeader: "Analyze Your Reports",
        reportsInstructions: "Paste the critical findings from your blood test or medical report below (e.g., 'HbA1c: 7.5%, Vitamin D: 12 ng/mL, TSH: 8.0'). Our system will explain the diagnosis.",
        reportsInputPlaceholder: "Enter findings here...",
        btnInterpretReport: "Interpret Report & Get Diagnosis",

        // Guidance
        guidanceMainHeader: "Targeted Nutritional Guidance",
        guidanceFindHeader: "Find Nutrients & Food Sources",
        guidanceInstructions: "Enter a medical condition, deficiency, or key symptoms (e.g., Iron deficiency, low energy, Type 2 Diabetes).",
        guidanceInputPlaceholder: "Enter diagnosis, deficiency, or symptoms (e.g., Vitamin B12 deficiency)",
        btnNutrientsAvoid: "Key Nutrients / Avoid",
        btnFoodSources: "Top Food Sources",
        btnInteractions: "Drug Interactions",
        guidanceOutputInitial: "Results will appear here after selecting an option above.",

        // Search
        searchMainHeader: "Grounded Health Search",
        searchInstructions: "Ask any health or nutrition question. The AI will use Google Search to provide the most up-to-date information.",
        searchInputPlaceholder: "e.g., latest research on intermittent fasting for diabetes",
        btnSearch: "Search with Google",
        searchResultsTitle: "Search Results",
        sourcesTitle: "Sources",
        searchInitialPrompt: "Your search results will appear here.",

        // Chat
        chatMainHeader: "AI Assistant",
        chatWelcome: "Hello! I'm your AI health assistant. How can I help you today with your diet, nutrition, or fitness questions?",
        chatInputPlaceholder: "Ask me anything about nutrition...",
        btnClearChat: "Clear Chat",

        // Feedback
        feedbackTitle: "Submit Feedback",
        feedbackType: "Feedback Type",
        feedbackTypeBug: "Bug Report",
        feedbackTypeSuggestion: "Suggestion",
        feedbackTypeGeneral: "General Comment",
        feedbackContent: "Your Feedback",
        btnSubmitFeedback: "Submit Feedback",
        feedbackSuccess: "Thank you! Your feedback has been saved.",
    },
    hi: {
        appTitle: "ट्रैक एंड ट्रीट - व्यक्तिगत पोषण",
        languageLabel: "भाषा",
        welcomeHeader: "ट्रैक एंड ट्रीट में आपका स्वागत है!",
        navDashboard: "डैशबोर्ड",
        navProfile: "प्रोफाइल और लक्ष्य",
        navPlan: "मेरा आहार योजना",
        navTracking: "ट्रैकिंग",
        navRecipes: "रेसिपी",
        navReports: "रिपोर्ट विश्लेषण",
        navGuidance: "पोषक तत्व मार्गदर्शन",
        navSearch: "स्वास्थ्य खोज",
        navChat: "एआई सहायक",
        navFeedback: "प्रतिक्रिया",
        
        dashSnapshotHeader: "आपका स्वास्थ्य स्नैपशॉट",
        dashBMI: "बीएमआई",
        dashBMICalc: "गणना के लिए विवरण दर्ज करें।",
        dashTarget: "दैनिक कैलोरी लक्ष्य",
        dashBaseGoal: "टीडीईई और लक्ष्य पर आधारित",
        dashWater: "आज का पानी",
        dashWaterGoal: "लक्ष्य: 3.5 लीटर",
        dashStreak: "योजना स्ट्रीक",
        dashKeepUp: "अच्छा काम करते रहें!",
        dashTipHeader: "ट्रैक एंड ट्रीट से आज की टिप",
        dashTipInitial: "कृपया अपनी व्यक्तिगत आहार युक्ति अनलॉक करने के लिए प्रोफ़ाइल विवरण भरें!",
        dashProgressHeader: "साप्ताहिक वजन घटाने की प्रगति",

        profileHeader: "आपके आवश्यक विवरण और लक्ष्य",
        metricHeader: "व्यक्तिगत मेट्रिक्स",
        labelName: "नाम",
        labelAge: "आयु (वर्ष)",
        labelGender: "लिंग",
        genderMale: "पुरुष",
        genderFemale: "महिला",
        genderOther: "अन्य",
        labelWeight: "वजन (किलो)",
        labelHeight: "ऊंचाई (सेमी)",
        labelActivity: "गतिविधि स्तर",
        activitySedentary: "निष्क्रिय (डेस्क की नौकरी)",
        activityLight: "हल्का (1-3 दिन/सप्ताह व्यायाम)",
        activityModerate: "मध्यम (3-5 दिन/सप्ताह व्यायाम)",
        activityHigh: "उच्च (6-7 दिन/सप्ताह व्यायाम)",
        activityExtreme: "अत्यधिक (एथलीट/भारी श्रम)",
        labelDiet: "आहार प्राथमिकता",
        dietVeg: "शाकाहारी",
        dietNonVeg: "मांसाहारी",
        dietVegan: "शाकाहारी (वीगन)",
        dietJain: "जैन",
        labelGoal: "प्राथमिक लक्ष्य",
        goalLoss: "वजन घटाना",
        goalGain: "वजन बढ़ाना",
        goalMaintain: "स्वास्थ्य रखरखाव",
        goalMuscle: "मांसपेशियों का लाभ",
        medicalHeader: "चिकित्सा और प्राथमिकताएँ (विशेष विवरण)",
        labelCondition: "चिकित्सा स्थितियां (मधुमेह, पीसीओएस, थायराइड, आदि)",
        labelAllergies: "एलर्जी और असहिष्णुता",
        labelDislikes: "नापसंद / पसंद के खाद्य पदार्थ",
        labelProfilePhoto: "प्रोफ़ाइल फ़ोटो",
        btnSaveProfile: "प्रोफाइल सहेजें और मूल्यांकन उत्पन्न करें",
        btnAiSummary: "✨ एआई स्वास्थ्य सारांश प्राप्त करें",
        aiSummaryTitle: "एआई स्वास्थ्य सारांश",
        macroGoalsHeader: "मैक्रोन्यूट्रिएंट लक्ष्य (ग्राम)",
        labelProteinGoal: "प्रोटीन लक्ष्य (ग्राम)",
        labelCarbGoal: "कार्बोहाइड्रेट लक्ष्य (ग्राम)",
        labelFatGoal: "वसा लक्ष्य (ग्राम)",
        assessmentHeader: "आपका स्वास्थ्य मूल्यांकन सारांश",
        calcBMI: "बीएमआई",
        calcBMIStatus: "बीएमआई स्थिति",
        calcTDEE: "टीडीईई",
        calcReqCals: "आवश्यक कैलोरी",
        calcProtein: "प्रोटीन लक्ष्य",
        calcCarbs: "कार्ब्स लक्ष्य",
        calcFat: "वसा लक्ष्य",
        macroHeader: "अनुमानित मैक्रोन्यूट्रिएंट वितरण:",

        planHeader: "मेरी आहार योजना",
        btnGeneratePlan: "✨ विस्तृत 3-दिवसीय योजना बनाएं",
        planInitialPrompt: "स्थिर योजना देखने के लिए अपनी प्रोफ़ाइल विवरण सहेजें, या कस्टम भोजन योजना के लिए एआई प्लानर का उपयोग करने हेतु '✨ विस्तृत 3-दिवसीय योजना बनाएं' बटन पर क्लिक करें!",

        trackerHeader: "अपने दैनिक सेवन को ट्रैक करें",
        logHeader: "भोजन लॉग",
        btnAnalyzeLog: "✨ लॉग का विश्लेषण करें",
        logAnalysisTitle: "लॉग विश्लेषण:",
        logEmpty: "आपका दैनिक भोजन लॉग यहां दिखाई देगा।",
        logInputPlaceholder: "अपना भोजन लॉग करें (उदा. दोपहर का भोजन: 1 कटोरी राजमा, चावल, सलाद) और मात्रा",
        logBtn: "भोजन लॉग करें",
        waterHeader: "पानी का सेवन",
        waterGoal: "लक्ष्य: 3.5 लीटर",
        btnAddWater: "+ 250मि.ली.",
        servingsHeader: "फल/सब्जी सर्विंग",
        btnAddServing: "+ सर्विंग जोड़ें",
        reminderHeader: "अनुपालन अनुस्मारक",
        reminderText: "बेहतर अनुपालन के लिए नीचे कस्टम भोजन और पानी के अनुस्मारक सेट करें!",
        btnSetReminder: "अनुस्मारक सेट करें",
        btnHideReminders: "अनुस्मारक छिपाएं",
        newReminder: "नया अनुस्मारक",
        reminderTime: "समय",
        reminderType: "प्रकार",
        reminderMeal: "भोजन",
        reminderWater: "पानी",
        btnAddReminder: "अनुस्मारक जोड़ें",
        noRemindersSet: "अभी तक कोई अनुस्मारक सेट नहीं है।",

        recipesMainHeader: "व्यक्तिगत रेसिपी और सामग्री अन्वेषक",
        recipeDiagHeader: "मेरी स्थिति के लिए रेसिपी",
        recipeDiagStatus: "अपनी सहेजी गई चिकित्सीय स्थिति के आधार पर विशिष्ट रेसिपी बनाने के लिए नीचे क्लिक करें",
        btnGenerateDiag: "स्थिति के लिए रेसिपी बनाएं",
        recipeIngrHeader: "अभिनव सामग्री रेसिपी",
        ingrInputPlaceholder: "एक मुख्य सामग्री दर्ज करें (उदा. पनीर, बाजरा, भिंडी)",
        btnSuggestRecipes: "3 अभिनव रेसिपी सुझाएं",
        
        reportsMainHeader: "चिकित्सा रिपोर्ट की व्याख्या",
        reportsAnalyzeHeader: "अपनी रिपोर्ट का विश्लेषण करें",
        reportsInstructions: "नीचे अपनी रक्त परीक्षण या चिकित्सा रिपोर्ट के महत्वपूर्ण निष्कर्ष पेस्ट करें (उदा. 'एचबीए1सी: 7.5%, विटामिन डी: 12 एनजी/एमएल, टीएसएच: 8.0')। हमारा सिस्टम निदान समझाएगा।",
        reportsInputPlaceholder: "निष्कर्ष यहां दर्ज करें...",
        btnInterpretReport: "रिपोर्ट की व्याख्या करें और निदान प्राप्त करें",

        guidanceMainHeader: "लक्षित पोषण मार्गदर्शन",
        guidanceFindHeader: "पोषक तत्व और खाद्य स्रोत खोजें",
        guidanceInstructions: "एक चिकित्सीय स्थिति, कमी, या मुख्य लक्षण दर्ज करें (उदा. आयरन की कमी, कम ऊर्जा, टाइप 2 मधुमेह)।",
        guidanceInputPlaceholder: "निदान, कमी, या लक्षण दर्ज करें (उदा. विटामिन बी12 की कमी)",
        btnNutrientsAvoid: "मुख्य पोषक तत्व / बचें",
        btnFoodSources: "शीर्ष खाद्य स्रोत",
        btnInteractions: "दवा परस्पर क्रिया",
        guidanceOutputInitial: "ऊपर दिए गए विकल्प का चयन करने के बाद परिणाम यहां दिखाई देंगे।",

        // Search
        searchMainHeader: "ग्राउंडेड स्वास्थ्य खोज",
        searchInstructions: "कोई भी स्वास्थ्य या पोषण संबंधी प्रश्न पूछें। एआई सबसे अद्यतित जानकारी प्रदान करने के लिए गूगल खोज का उपयोग करेगा।",
        searchInputPlaceholder: "उदा., मधुमेह के लिए रुक-रुक कर उपवास पर नवीनतम शोध",
        btnSearch: "गूगल से खोजें",
        searchResultsTitle: "खोज के परिणाम",
        sourcesTitle: "स्रोत",
        searchInitialPrompt: "आपके खोज परिणाम यहां दिखाई देंगे।",
        
        // Chat
        chatMainHeader: "एआई सहायक",
        chatWelcome: "नमस्ते! मैं आपका एआई स्वास्थ्य सहायक हूं। आज मैं आपके आहार, पोषण, या फिटनेस संबंधी सवालों में कैसे मदद कर सकता हूं?",
        chatInputPlaceholder: "पोषण के बारे में कुछ भी पूछें...",
        btnClearChat: "चैट साफ़ करें",

        // Feedback
        feedbackTitle: "प्रतिक्रिया भेजें",
        feedbackType: "प्रतिक्रिया का प्रकार",
        feedbackTypeBug: "बग रिपोर्ट",
        feedbackTypeSuggestion: "सुझाव",
        feedbackTypeGeneral: "सामान्य टिप्पणी",
        feedbackContent: "आपकी प्रतिक्रिया",
        btnSubmitFeedback: "प्रतिक्रिया भेजें",
        feedbackSuccess: "धन्यवाद! आपकी प्रतिक्रिया सहेज ली गई है।",
    },
    gu: {
        appTitle: "ટ્રેક એન્ડ ટ્રીટ - વ્યક્તિગત આહારશાસ્ત્ર",
        languageLabel: "ભાષા",
        welcomeHeader: "ટ્રેક એન્ડ ટ્રીટમાં તમારું સ્વાગત છે!",
        navDashboard: "ડેશબોર્ડ",
        navProfile: "પ્રોફાઇલ અને લક્ષ્યો",
        navPlan: "મારો આહાર પ્લાન",
        navTracking: "ટ્રેકિંગ",
        navRecipes: "વાનગીઓ",
        navReports: "રિપોર્ટ વિશ્લેષણ",
        navGuidance: "પોષક માર્ગદર્શન",
        navSearch: "આરોગ્ય શોધ",
        navChat: "AI સહાયક",
        navFeedback: "પ્રતિસાદ",
        
        dashSnapshotHeader: "તમારો સ્વાસ્થ્ય સ્નેપશોટ",
        dashBMI: "BMI",
        dashBMICalc: "ગણતરી માટે વિગતો દાખલ કરો.",
        dashTarget: "દૈનિક કેલરી લક્ષ્ય",
        dashBaseGoal: "TDEE અને લક્ષ્ય પર આધારિત",
        dashWater: "આજનું પાણી",
        dashWaterGoal: "લક્ષ્ય: 3.5 લિટર",
        dashStreak: "પ્લાન સ્ટ્રીક",
        dashKeepUp: "આટલું સારું કામ કરતા રહો!",
        dashTipHeader: "ટ્રેક એન્ડ ટ્રીટ તરફથી આજની ટિપ",
        dashTipInitial: "તમારી વ્યક્તિગત આહાર ટિપ અનલૉક કરવા માટે કૃપા કરીને તમારી પ્રોફાઇલ વિગતો પૂર્ણ કરો!",
        dashProgressHeader: "સાપ્તાહિક વજન ઘટાડવાની પ્રગતિ",

        profileHeader: "તમારી આવશ્યક વિગતો અને લક્ષ્યો",
        metricHeader: "વ્યક્તિગત મેટ્રિક્સ",
        labelName: "નામ",
        labelAge: "ઉંમર (વર્ષ)",
        labelGender: "લિંગ",
        genderMale: "પુરુષ",
        genderFemale: "સ્ત્રી",
        genderOther: "અન્ય",
        labelWeight: "વજન (કિલો)",
        labelHeight: "ઊંચાઈ (સેમી)",
        labelActivity: "પ્રવૃત્તિ સ્તર",
        activitySedentary: "બેઠાડુ (ડેસ્ક જોબ)",
        activityLight: "હળવું (1-3 દિવસ/અઠવાડિયું કસરત)",
        activityModerate: "મધ્યમ (3-5 દિવસ/અઠવાડિયું કસરત)",
        activityHigh: "ઉચ્ચ (6-7 દિવસ/અઠવાડિયું કસરત)",
        activityExtreme: "અત્યંત (એથ્લેટ/ભારે શ્રમ)",
        labelDiet: "આહાર પસંદગી",
        dietVeg: "શાકાહારી",
        dietNonVeg: "માંસાહારી",
        dietVegan: "શાકાહારી (વેગન)",
        dietJain: "જૈન",
        labelGoal: "પ્રાથમિક લક્ષ્ય",
        goalLoss: "વજન ઘટાડવું",
        goalGain: "વજન વધારવું",
        goalMaintain: "સ્વાસ્થ્ય જાળવણી",
        goalMuscle: "સ્નાયુ લાભ",
        medicalHeader: "તબીબી અને પસંદગીઓ (વિશિષ્ટ વિગતો)",
        labelCondition: "તબીબી સ્થિતિઓ (ડાયાબિટીસ, પીસીઓએસ, થાઇરોઇડ, વગેરે)",
        labelAllergies: "એલર્જી અને અસહિષ્ણુતા",
        labelDislikes: "નાપસંદ / પસંદગીના ખોરાક",
        labelProfilePhoto: "પ્રોફાઇલ ફોટો",
        btnSaveProfile: "પ્રોફાઇલ સાચવો અને મૂલ્યાંકન જનરેટ કરો",
        btnAiSummary: "✨ AI આરોગ્ય સારાંશ મેળવો",
        aiSummaryTitle: "AI આરોગ્ય સારાંશ",
        macroGoalsHeader: "મેક્રોન્યુટ્રિઅન્ટ લક્ષ્યો (ગ્રામ)",
        labelProteinGoal: "પ્રોટીન લક્ષ્ય (ગ્રામ)",
        labelCarbGoal: "કાર્બોહાઇડ્રેટ લક્ષ્ય (ગ્રામ)",
        labelFatGoal: "ચરબીનું લક્ષ્ય (ગ્રામ)",
        assessmentHeader: "તમારો સ્વાસ્થ્ય મૂલ્યાંકન સારાંશ",
        calcBMI: "BMI",
        calcBMIStatus: "BMI સ્થિતિ",
        calcTDEE: "TDEE",
        calcReqCals: "જરૂરી કેલરી",
        calcProtein: "પ્રોટીન લક્ષ્ય",
        calcCarbs: "કાર્બ્સ લક્ષ્ય",
        calcFat: "ફેટ લક્ષ્ય",
        macroHeader: "અંદાજિત મેક્રોન્યુટ્રિઅન્ટ વિતરણ:",

        planHeader: "મારો આહાર પ્લાન",
        btnGeneratePlan: "✨ વિગતવાર 3-દિવસીય પ્લાન જનરેટ કરો",
        planInitialPrompt: "કૃપા કરીને સ્થિર પ્લાન જોવા માટે તમારી પ્રોફાઇલ વિગતો સાચવો, અથવા કસ્ટમ ભોજન યોજના માટે AI પ્લાનરનો ઉપયોગ કરવા માટે '✨ વિગતવાર 3-દિવસીય પ્લાન જનરેટ કરો' બટન પર ક્લિક કરો!",
        
        trackerHeader: "તમારા દૈનિક સેવનને ટ્રૅક કરો",
        logHeader: "ભોજન લોગ",
        btnAnalyzeLog: "✨ લોગનું વિશ્લેષણ કરો",
        logAnalysisTitle: "લોગ વિશ્લેષણ:",
        logEmpty: "તમારો દૈનિક ભોજન લોગ અહીં દેખાશે.",
        logInputPlaceholder: "તમારું ભોજન લોગ કરો (દા.ત. લંચ: 1 વાટકી રાજમા, ભાત, સલાડ) અને જથ્થો",
        logBtn: "ભોજન લોગ કરો",
        waterHeader: "પાણીનું સેવન",
        waterGoal: "લક્ષ્ય: 3.5 લિટર",
        btnAddWater: "+ 250મિલી",
        servingsHeader: "ફળ/શાકભાજી સર્વિંગ",
        btnAddServing: "+ સર્વિંગ ઉમેરો",
        reminderHeader: "અનુપાલન રીમાઇન્ડર્સ",
        reminderText: "વધારે સારા અનુપાલન માટે નીચે કસ્ટમ ભોજન અને પાણીના રીમાઇન્ડર્સ સેટ કરો!",
        btnSetReminder: "રીમાઇન્ડર્સ સેટ કરો",
        btnHideReminders: "રીમાઇન્ડર્સ છુપાવો",
        newReminder: "નવું રીમાઇન્ડર",
        reminderTime: "સમય",
        reminderType: "પ્રકાર",
        reminderMeal: "ભોજન",
        reminderWater: "પાણી",
        btnAddReminder: "રીમાઇન્ડર ઉમેરો",
        noRemindersSet: "હજી સુધી કોઈ રીમાઇન્ડર સેટ નથી.",

        recipesMainHeader: "વ્યક્તિગત વાનગીઓ અને સામગ્રી એક્સપ્લોરર",
        recipeDiagHeader: "મારી સ્થિતિ માટે વાનગીઓ",
        recipeDiagStatus: "તમારી સાચવેલી તબીબી સ્થિતિ પર આધારિત વિશિષ્ટ વાનગીઓ જનરેટ કરવા માટે નીચે ક્લિક કરો",
        btnGenerateDiag: "સ્થિતિ માટે વાનગીઓ જનરેટ કરો",
        recipeIngrHeader: "નવીન સામગ્રી વાનગીઓ",
        ingrInputPlaceholder: "એક મુખ્ય સામગ્રી દાખલ કરો (દા.ત. પનીર, બાજરી, ભીંડો)",
        btnSuggestRecipes: "3 નવીન વાનગીઓ સૂચવો",
        
        reportsMainHeader: "તબીબી રિપોર્ટ અર્થઘટન",
        reportsAnalyzeHeader: "તમારા રિપોર્ટનું વિશ્લેષણ કરો",
        reportsInstructions: "નીચે તમારા રક્ત પરીક્ષણ અથવા તબીબી રિપોર્ટના નિર્ણાયક તારણો પેસ્ટ કરો (દા.ત. 'HbA1c: 7.5%, વિટામિન D: 12 ng/mL, TSH: 8.0') . અમારી સિસ્ટમ નિદાન સમજાવશે.",
        reportsInputPlaceholder: "તારણો અહીં દાખલ કરો...",
        btnInterpretReport: "રિપોર્ટનો અર્થઘટન કરો અને નિદાન મેળવો",

        guidanceMainHeader: "લક્ષિત પોષક માર્ગદર્શન",
        guidanceFindHeader: "પોષક તત્વો અને ખોરાકના સ્ત્રોત શોધો",
        guidanceInstructions: "તબીબી સ્થિતિ, ઉણપ, અથવા મુખ્ય લક્ષણો દાખલ કરો (દા.ત. આયર્નની ઉણપ, ઓછી ઊર્જા, ટાઇપ 2 ડાયાબિટીસ).",
        guidanceInputPlaceholder: "નિદાન, ઉણપ, અથવા લક્ષણો દાખલ કરો (દા.ત. વિટામિન B12 ની ઉણપ)",
        btnNutrientsAvoid: "મુખ્ય પોષક તત્વો / ટાળો",
        btnFoodSources: "ટોચના ખોરાકના સ્ત્રોતો",
        btnInteractions: "દવાઓની ક્રિયાપ્રતિક્રિયા",
        guidanceOutputInitial: "ઉપરના વિકલ્પની પસંદગી કર્યા પછી પરિણામો અહીં દેખાશે.",

        // Search
        searchMainHeader: "ગ્રાઉન્ડેડ આરોગ્ય શોધ",
        searchInstructions: "કોઈપણ આરોગ્ય અથવા પોષણ સંબંધિત પ્રશ્ન પૂછો. AI સૌથી અદ્યતન માહિતી પ્રદાન કરવા માટે Google શોધનો ઉપયોગ કરશે.",
        searchInputPlaceholder: "દા.ત., ડાયાબિટીસ માટે તૂટક તૂટક ઉપવાસ પર નવીનતમ સંશોધન",
        btnSearch: "Google વડે શોધો",
        searchResultsTitle: "શોધ પરિણામો",
        sourcesTitle: "સ્ત્રોતો",
        searchInitialPrompt: "તમારા શોધ પરિણામો અહીં દેખાશે.",
        
        // Chat
        chatMainHeader: "AI સહાયક",
        chatWelcome: "નમસ્તે! હું તમારો AI આરોગ્ય સહાયક છું. આજે હું તમારા આહાર, પોષણ, અથવા ફિટનેસ સંબંધિત પ્રશ્નોમાં કેવી રીતે મદદ કરી શકું?",
        chatInputPlaceholder: "પોષણ વિશે કંઈપણ પૂછો...",
        btnClearChat: "ચેટ સાફ કરો",

        // Feedback
        feedbackTitle: "પ્રતિસાદ સબમિટ કરો",
        feedbackType: "પ્રતિસાદનો પ્રકાર",
        feedbackTypeBug: "બગ રિપોર્ટ",
        feedbackTypeSuggestion: "સૂચન",
        feedbackTypeGeneral: "સામાન્ય ટિપ્પણી",
        feedbackContent: "તમારો પ્રતિસાદ",
        btnSubmitFeedback: "પ્રતિસાદ સબમિટ કરો",
        feedbackSuccess: "આભાર! તમારો પ્રતિસાદ સાચવવામાં આવ્યો છે.",
    },
};
